databases:
- name: Rails_Okeb_API
  databaseName: okeb_rails_api_production
  user: okebcode

services:
- type: web
  name: Rails_Okeb_API
  env: ruby
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec puma -C config/puma.rb"
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: okeb_rails_api_production
      property: connectionString
  - key: 73f1dbc0ba511fb35b885235bd46060c
    sync: false
