databases:
- name: Rails_Okeb_API
  databaseName: rails_api_production
  user: oliver

services:
- type: web
  name: Rails_Okeb_API
  env: ruby
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec puma -C config/puma.rb"
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: rails_api_production
      property: connectionString
  - key: RAILS_MASTER_KEY
    sync: false
