databases:
- name: Rails_Okeb_API
  databaseName: rails_api_production
  user: oliver

services:
- type: web
  name: Rails_Okeb_API
  env: ruby
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec puma -C config/puma.rb"
  envVars:
  - key: dpg-cgilkl7dvk4vd54bioq0-a
    fromDatabase:
      name: rails_api_production
      property: connectionString
  - key: 73f1dbc0ba511fb35b885235bd46060c
    sync: false
